"""
core/process_logger.py - Structured JSON Process Logger & Telemetry for AI Agents.
100% Python Standard Library. Generates machine-readable execution traces and performance telemetry.
"""
from typing import Dict, Any, Optional, List
from pathlib import Path
import os
import sys
import json
import time
import uuid
from datetime import datetime, timezone

from core.config import BASE_DIR

LOG_DIR = BASE_DIR / "logs" / "process"
RUNS_DIR = LOG_DIR / "runs"
LATEST_RUN_PATH = LOG_DIR / "latest_run.json"
HISTORY_PATH = LOG_DIR / "history.jsonl"
METRICS_PATH = LOG_DIR / "metrics_summary.json"
README_PATH = LOG_DIR / "README.md"
MAX_STORED_RUNS = 500


def _ensure_log_environment():
    """Initializes log directories and README documentation for AI agents."""
    RUNS_DIR.mkdir(parents=True, exist_ok=True)
    if not README_PATH.exists():
        _create_agent_readme()


def _create_agent_readme():
    """Generates schema reference documentation for AI Agents."""
    content = """# Process Logs Directory (AI Agent Guide)

This directory contains execution traces designed specifically for AI Agents to inspect pipeline telemetry, diagnose latency bottlenecks, and execute automated optimization cycles.

## Files
- `latest_run.json`: Full JSON trace of the most recent image processing request. Inspect this file first for immediate state analysis.
- `history.jsonl`: Append-only JSON Lines stream recording historical runs for trend analysis and regression detection.
- `metrics_summary.json`: Aggregated statistics including total runs, average latency, P50/P95 latency, and bottleneck distributions.
- `runs/run_<timestamp>_<id>.json`: Individual execution traces with microsecond precision per pipeline stage.

## Pipeline Stages Logged
1. `stage_1_validation`: File header verification, size check, EXIF orientation normalization.
2. `stage_2_dhash_guard`: 64-bit perceptual hash computation and O(1) blocklist Hamming distance check.
3. `stage_3_nsfw_guard`: Local CPU ONNX CNN classification and dynamic rule threshold evaluation.
4. `stage_4_yolo_detection`: YOLOv8 object detection, bounding box regression, and NumPy NMS.
5. `stage_5_user_profiling`: Hobby taxonomy matching, social context classification, and memory caption generation.

## Agent Optimization Fields
- `performance_breakdown.bottleneck_stage`: The stage consuming the largest proportion of total execution time.
- `agent_telemetry.optimization_opportunities`: Suggested optimization targets generated by the system.
"""
    with open(README_PATH, "w", encoding="utf-8") as f:
        f.write(content.strip() + "\n")


class PipelineTracer:
    """Microsecond-precision tracer for a single image execution lifecycle."""

    def __init__(self, client_info: Optional[Dict[str, Any]] = None):
        _ensure_log_environment()
        self.trace_id = f"trace_{datetime.now(timezone.utc).strftime('%Y%m%d_%H%M%S')}_{uuid.uuid4().hex[:6]}"
        self.start_wall_time = datetime.now(timezone.utc).isoformat()
        self.start_perf_time = time.perf_counter()
        self.client_info = client_info or {}
        self.image_meta: Dict[str, Any] = {}
        self.stages: Dict[str, Dict[str, Any]] = {}

    def set_image_meta(self, meta: Dict[str, Any]):
        self.image_meta = meta

    def record_stage(
        self,
        stage_name: str,
        status: str,
        latency_ms: float,
        details: Optional[Dict[str, Any]] = None,
    ):
        """Records telemetry for an individual pipeline stage."""
        self.stages[stage_name] = {
            "status": status,
            "latency_ms": round(latency_ms, 2),
            "details": details or {},
        }

    def finish(
        self,
        is_allowed: bool,
        guard_summary: Optional[Dict[str, Any]] = None,
        profile_summary: Optional[Dict[str, Any]] = None,
        db_record: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """Finalizes the trace, evaluates bottlenecks, and commits log files."""
        total_latency_ms = (time.perf_counter() - self.start_perf_time) * 1000.0

        # Calculate latency percentages & find bottleneck
        percentages: Dict[str, str] = {}
        bottleneck_stage = "none"
        max_stage_ms = -1.0

        for stage_name, s_data in self.stages.items():
            ms = s_data.get("latency_ms", 0.0)
            pct = (ms / total_latency_ms * 100.0) if total_latency_ms > 0 else 0.0
            percentages[stage_name] = f"{pct:.1f}%"
            if ms > max_stage_ms:
                max_stage_ms = ms
                bottleneck_stage = stage_name

        # Generate intelligent suggestions for AI Agent
        opportunities = []
        if bottleneck_stage == "stage_4_yolo_detection" and max_stage_ms > 35.0:
            opportunities.append({
                "target": "stage_4_yolo_detection",
                "reason": f"YOLOv8 inference consumes {percentages.get('stage_4_yolo_detection', 'N/A')} of total latency ({max_stage_ms:.1f}ms).",
                "suggestions": [
                    "Bật skip_profile=true nếu mobile client chỉ cần kiểm duyệt nhanh.",
                    "Giảm kích thước tiền xử lý hoặc chạy detector theo hàng đợi nền (asynchronous worker).",
                ],
            })
        elif bottleneck_stage == "stage_3_nsfw_guard" and max_stage_ms > 25.0:
            opportunities.append({
                "target": "stage_3_nsfw_guard",
                "reason": f"NSFW CNN inference chiếm {percentages.get('stage_3_nsfw_guard', 'N/A')} thời gian ({max_stage_ms:.1f}ms).",
                "suggestions": [
                    "Cân nhắc lượng tử hóa ONNX INT8 (Quantization) để tăng tốc độ trên CPU.",
                ],
            })

        fail_fast_triggered = self.stages.get("stage_4_yolo_detection", {}).get("status") == "SKIPPED"

        trace_data = {
            "trace_id": self.trace_id,
            "timestamp": self.start_wall_time,
            "client_request": self.client_info,
            "image_metadata": self.image_meta,
            "outcome": {
                "allowed": is_allowed,
                "fail_fast_triggered": fail_fast_triggered,
                "guard": guard_summary,
                "profile": profile_summary,
            },
            "merged_tags": profile_summary.get("merged_tags", []) if profile_summary else [],
            "database_payload": db_record,
            "pipeline_stages": self.stages,
            "performance_breakdown": {
                "total_latency_ms": round(total_latency_ms, 2),
                "stages_percentage": percentages,
                "bottleneck_stage": bottleneck_stage,
            },
            "agent_telemetry": {
                "fail_fast_triggered": fail_fast_triggered,
                "optimization_opportunities": opportunities,
            },
        }

        # Persist traces
        ProcessLogger.save_trace(trace_data)
        return trace_data


class ProcessLogger:
    """Manages disk persistence, latest trace pointer, and rolling metrics summary."""

    @staticmethod
    def save_trace(trace_data: Dict[str, Any]):
        try:
            _ensure_log_environment()
            trace_id = trace_data["trace_id"]
            run_file = RUNS_DIR / f"{trace_id}.json"

            json_str = json.dumps(trace_data, indent=2, ensure_ascii=False)

            # 1. Write individual run trace file
            with open(run_file, "w", encoding="utf-8") as f:
                f.write(json_str)

            # 2. Update latest_run.json atomically
            temp_latest = LATEST_RUN_PATH.with_suffix(".tmp")
            with open(temp_latest, "w", encoding="utf-8") as f:
                f.write(json_str)
            if temp_latest.exists():
                temp_latest.replace(LATEST_RUN_PATH)

            # 3. Append to history.jsonl (compact 1-line per run)
            summary_record = {
                "trace_id": trace_id,
                "timestamp": trace_data.get("timestamp"),
                "allowed": trace_data.get("outcome", {}).get("allowed", True),
                "total_latency_ms": trace_data.get("performance_breakdown", {}).get("total_latency_ms", 0.0),
                "bottleneck": trace_data.get("performance_breakdown", {}).get("bottleneck_stage"),
                "primary_interest": trace_data.get("outcome", {}).get("profile", {}).get("primary_interest") if trace_data.get("outcome", {}).get("profile") else None,
            }
            with open(HISTORY_PATH, "a", encoding="utf-8") as f:
                f.write(json.dumps(summary_record, ensure_ascii=False) + "\n")

            # 4. Update rolling summary metrics
            ProcessLogger._update_metrics(trace_data)

            # 5. Maintain FIFO rotation
            ProcessLogger._prune_old_runs()

        except Exception as err:
            sys.stderr.write(f"[ProcessLogger Warning] Failed to log trace: {err}\n")

    @staticmethod
    def _update_metrics(trace_data: Dict[str, Any]):
        """Maintains rolling aggregate metrics for AI Agent queries."""
        metrics: Dict[str, Any] = {
            "total_runs": 0,
            "allowed_count": 0,
            "blocked_count": 0,
            "avg_latency_ms": 0.0,
            "bottlenecks_distribution": {},
            "last_updated": datetime.now(timezone.utc).isoformat(),
        }

        if METRICS_PATH.exists():
            try:
                with open(METRICS_PATH, "r", encoding="utf-8") as f:
                    metrics = json.load(f)
            except Exception:
                pass

        total = metrics.get("total_runs", 0) + 1
        is_allowed = trace_data.get("outcome", {}).get("allowed", True)
        curr_latency = trace_data.get("performance_breakdown", {}).get("total_latency_ms", 0.0)
        old_avg = metrics.get("avg_latency_ms", 0.0)

        metrics["total_runs"] = total
        if is_allowed:
            metrics["allowed_count"] = metrics.get("allowed_count", 0) + 1
        else:
            metrics["blocked_count"] = metrics.get("blocked_count", 0) + 1

        metrics["avg_latency_ms"] = round(((old_avg * (total - 1)) + curr_latency) / total, 2)
        metrics["last_updated"] = datetime.now(timezone.utc).isoformat()

        # Bottlenecks distribution
        b_stage = trace_data.get("performance_breakdown", {}).get("bottleneck_stage", "unknown")
        b_dist = metrics.get("bottlenecks_distribution", {})
        b_dist[b_stage] = b_dist.get(b_stage, 0) + 1
        metrics["bottlenecks_distribution"] = b_dist

        try:
            with open(METRICS_PATH, "w", encoding="utf-8") as f:
                json.dump(metrics, f, indent=2, ensure_ascii=False)
        except Exception:
            pass

    @staticmethod
    def _prune_old_runs():
        """FIFO deletion if runs exceed MAX_STORED_RUNS."""
        try:
            runs = sorted(RUNS_DIR.glob("*.json"), key=lambda p: p.stat().st_mtime)
            if len(runs) > MAX_STORED_RUNS:
                for file_to_remove in runs[: len(runs) - MAX_STORED_RUNS]:
                    file_to_remove.unlink()
        except Exception:
            pass

    @staticmethod
    def get_latest_run() -> Optional[Dict[str, Any]]:
        """Reads latest_run.json."""
        if LATEST_RUN_PATH.exists():
            try:
                with open(LATEST_RUN_PATH, "r", encoding="utf-8") as f:
                    return json.load(f)
            except Exception:
                return None
        return None

    @staticmethod
    def get_summary() -> Dict[str, Any]:
        """Reads metrics_summary.json."""
        if METRICS_PATH.exists():
            try:
                with open(METRICS_PATH, "r", encoding="utf-8") as f:
                    return json.load(f)
            except Exception:
                pass
        return {"total_runs": 0, "status": "No runs recorded yet"}
